export const data = [
  {
    key: '1',
    item: '1',
    color: 'red',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
    images: [
      require('../assets/images/p2.jpg'),
      require('../assets/images/p1.jpg'),
      require('../assets/images/p2.jpg'),
      require('../assets/images/p1.jpg'),
      require('../assets/images/p2.jpg'),
      require('../assets/images/p1.jpg'),
      require('../assets/images/p2.jpg'),
    ],
  },
  {
    key: '2',
    item: '2',
    color: 'blue',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '3',
    item: '3',
    color: 'yellow',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '4',
    item: '4',
    color: 'green',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '5',
    item: '5',
    color: 'red',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '6',
    item: '6',
    color: 'blue',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '7',
    item: '7',
    color: 'yellow',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '8',
    item: '8',
    color: 'green',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '9',
    item: '9',
    color: 'red',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '10',
    item: '10',
    color: 'blue',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '11',
    item: '11',
    color: 'yellow',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '12',
    item: '12',
    color: 'green',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '13',
    item: '13',
    color: 'red',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '14',
    item: '14',
    color: 'blue',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '15',
    item: '15',
    color: 'yellow',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '16',
    item: '16',
    color: 'green',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '17',
    item: '17',
    color: 'green',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '18',
    item: '18',
    color: 'red',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '19',
    item: '19',
    color: 'blue',
    image: require('../assets/images/t2.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
  {
    key: '20',
    item: '20',
    color: 'yellow',
    image: require('../assets/images/t1.jpg'),
    pImg: require('../assets/images/p1.jpg'),
  },
];
